# Generated by Django 3.1.6 on 2021-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rule_files_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('f_type', models.CharField(max_length=20)),
                ('f_date', models.DateField()),
                ('f_discription', models.TextField()),
            ],
        ),
    ]
