# Generated by Django 3.1.6 on 2021-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('r_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('r_name', models.CharField(max_length=70)),
                ('r_type', models.CharField(max_length=20)),
                ('r_date', models.DateField()),
                ('r_discription', models.TextField()),
                ('r_file', models.TextField()),
                ('r_selected', models.IntegerField(default=0)),
            ],
        ),
    ]
